# Regions
Region.find_or_create_by(name: 'Cape Town')
Region.find_or_create_by(name: 'The Northern Cape')
Region.find_or_create_by(name: 'The Western Cape')
Region.find_or_create_by(name: 'KwaZulu-Natal')
Region.find_or_create_by(name: 'Free State')
Region.find_or_create_by(name: 'Gauteng')
Region.find_or_create_by(name: 'North West Province')
Region.find_or_create_by(name: 'Mpumalanga')
Region.find_or_create_by(name: 'Limpopo')
